apiVersion: 1

datasources:
  - name: Prometheus
    uid: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Elasticsearch Logs
    uid: ElasticsearchLogs
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: baemin-logs-*
    editable: true
    jsonData:
      interval: Daily
      timeField: "@timestamp"
